## \file device_tree_helpers.tcl

# \var dtsi_output_path
#Location where the output dtsi/dtsi_chunk/dtsi_post_chunk files will be put
global dtsi_output_path ;set dtsi_output_path "${DTSI_PATH}"

# Global variable \c axi_memory_mappings_addr
# A global variable containing all the address assignments.  Used for package and header listings of endpoint to address
global axi_memory_mappings_addr;  set axi_memory_mappings_addr  [dict create]
# Global variable \c axi_memory_mappings_range
# A global variable containing all the address range assignments.  Used for package and header listings of endpoint to address ranges
global axi_memory_mappings_range; set axi_memory_mappings_range [dict create]

# Global variable \c default_device_tree_additions
# The default device tree values
global default_device_tree_additions; set default_device_tree_additions "        compatible = \"generic-uio\";\n        label = \"\$device_name\";\n        linux,uio-name = \"\$device_name\";\n"

source ${BD_PATH}/utils/vivado_version.tcl

#Find this device and add its AXI address and range to .h and .vhd files
proc BUILD_AXI_ADDR_TABLE {device_name {new_name  ""} } {
    global axi_memory_mappings_addr
    global axi_memory_mappings_range
    set addr_seg [get_bd_addr_segs -quiet *SEG*${device_name}]
    if {[string length ${addr_seg}] == 0} {
	set addr_seg [get_bd_addr_segs -regexp -quiet ".*SEG_${device_name}_(?:Control|Reg|Mem).*"]
    }
    puts ${addr_seg}
    if {[string length ${addr_seg}] >0} {
	#set addr [format %08X [lindex [get_property -quiet OFFSET ${addr_seg}] 0] ]
	set addr [lindex [get_property -quiet OFFSET ${addr_seg}] 0]
	#set addr_range [format %08X [lindex [get_property -quiet RANGE ${addr_seg}] 0] ]
	set addr_range [lindex [get_property -quiet RANGE ${addr_seg}] 0]
	set name $device_name
	if {[string length $new_name] > 0} {
	    set name $new_name
	}
	puts "  ${name}:  ${addr}:${addr_range}"
	dict set axi_memory_mappings_addr  ${name} ${addr}      
	dict set axi_memory_mappings_range ${name} ${addr_range}
    }
}

## proc \c AXI_DEV_UIO_DTSI_POST_CHUNK
#Arguments:
#  \param device_name Name of the device to generate the dtsi_post_chunk file for
#  \param dt_data Additional data for the device tree.  Default is a set by a global variable.
# This function writes a dtsi_post_chunk file to append a XILINX axi slave so it
#  can be used as a UIO device.
# This takes the name of the device (as it appears in the DTSI file generated by xilinx)
proc AXI_DEV_UIO_DTSI_POST_CHUNK [list device_name  [list dt_data $default_device_tree_additions]] {
    global dtsi_output_path
    
    assign_bd_address [get_bd_addr_segs {${device_name}/S_AXI/Reg }]
    puts "AXI_DEV_UIO_DTSI_POST_CHUNK: ${device_name}"

    BUILD_AXI_ADDR_TABLE ${device_name}

    #make sure the output folder exists
    file mkdir ${dtsi_output_path}
    set dtsi_file [open "${dtsi_output_path}/${device_name}.dtsi_post_chunk" w+]
    puts $dtsi_file "  &${device_name}{"

    #add device specific stuff
    set map {}
    lappend map {$device_name} $device_name
    puts  ${dtsi_file} [string map $map  ${dt_data}]

    puts $dtsi_file "  };"
    close $dtsi_file
}


## proc \c AXI_DEV_UIO_DTSI_CHUNK
#Arguments:
#  \param device_name Name of the device to generate the dtsi_chunk file for
#  \param dt_data Additional data for the device tree.  Default is a set by a global variable.
# This function writes a dtsi_chunk file to append a XILINX axi slave so it
#  can be used as a UIO device.
proc AXI_DEV_UIO_DTSI_CHUNK [list device_name  [list dt_data $default_device_tree_additions]] {
    global dtsi_output_path

    global REMOTE_C2C
    global REMOTE_C2C_64

    puts "AXI_DEV_UIO_DTSI_CHUNK: ${device_name}"

    BUILD_AXI_ADDR_TABLE ${device_name}

    set addr [format %X [lindex [get_property OFFSET [get_bd_addr_segs -regex .*SEG_${device_name}_(Reg|Control|Mem0).*]] 0] ]
    set addr_range [format %X [lindex [get_property RANGE [get_bd_addr_segs -regex .*SEG_${device_name}_(Reg|Control|Mem0).*]] 0] ]

    #make sure the output folder exists
    file mkdir ${dtsi_output_path}

    if { [expr [string first xc7z [get_parts -of_objects [get_projects] ] ] >= 0 ] || 
	 [info exists REMOTE_C2C] || 
	 [expr [package vcompare [clean_version] 2020.2 ] >=0] } {    
	#build dtsi file for this for later    
	set dtsi_file [open "${dtsi_output_path}/${device_name}.dtsi_chunk" w+]
	
	#handle amba_pl between 7 and USP
	set amba_path "  amba_pl"
	if { [expr [string first xc7z [get_parts -of_objects [get_projects] ] ] == -1 ] } {
	    set amba_path "${amba_path}@0"
	}
	puts $dtsi_file "${amba_path} {" 
	

	puts $dtsi_file "    axiSlave$device_name: $device_name@${addr} {"
	if { [expr [string length ${addr}] > 8 ] || 
	     [expr [string first xczu [get_parts -of_objects [get_projects] ] ] >= 0 ] ||
	     [info exists REMOTE_C2C_64] 
	 } {

	    set addr_MSB  [string range ${addr} 8 [string length ${addr}]]
	    if { [expr [string length $addr_MSB] == 0 ] } {
		set addr_MSB "0"
	    }
	    set addr_LSB  [string range ${addr} 0 7]

	    set range_MSB [string range ${addr_range} 8 [string length ${addr_range} ] ]
	    if { [expr [string length $range_MSB] == 0 ] } {
		set range_MSB "0"
	    }
	    set range_LSB [string range ${addr_range} 0 7]    

	    puts $dtsi_file "      reg = <0x${addr_MSB} 0x${addr_LSB} 0x${range_MSB} 0x${range_LSB}>;"
	} else {
	    puts $dtsi_file "      reg = <0x${addr} 0x${addr_range}>;"
	}
	#add additional parameters
	set map {}
	lappend map {$device_name} $device_name
	puts  ${dtsi_file} [string map $map  ${dt_data}]

	puts $dtsi_file "    };"
	puts $dtsi_file "  };"
	close $dtsi_file
    } else { 
	#build a dtsi_post_chunk file
	AXI_DEV_UIO_DTSI_POST_CHUNK ${device_name}
    }
}

## proc \c AXI_DEV_UIO_DTSI_OVERLAY
#Arguments:
#  \param device_name Name of the device to generate the dtsi_chunk file for
#  \param dt_data Additional data for the device tree.  Default is a set by a global variable.
# This function create a dtsi file for use as a dtsi overlay source file.
proc AXI_DEV_UIO_DTSI_OVERLAY [list device_name  manual_load_dtsi [list dt_data $default_device_tree_additions]] {
    global dtsi_output_path

    global REMOTE_C2C
    global REMOTE_C2C_64

    BUILD_AXI_ADDR_TABLE ${device_name}

    set addr_segs [get_bd_addr_segs -regex .*SEG_${device_name}_(Reg|Control|Mem0).*]
    if { [llength ${addr_segs} ] == 0 } {
	puts "Cannont find address segments for $device_name"
	error "Cannont find address segments for $device_name"
    }
    set addr [format %X [lindex [get_property OFFSET ${addr_segs}] 0] ]
    set addr_range [format %X [lindex [get_property RANGE ${addr_segs}] 0] ]

    #build dtsi file for this for later    
    if { ${manual_load_dtsi} == 0} {
	#make sure the output folder exists
	file mkdir ${dtsi_output_path}
	set dtsi_filename "${dtsi_output_path}/${device_name}.dtsi"
    } else {
	#make sure the output folder exists
	file mkdir ${dtsi_output_path}/manual_load

	set dtsi_filename "${dtsi_output_path}/manual_load/${device_name}.dtsi"
    }
    set dtsi_file [open ${dtsi_filename}  w+]
    
    set amba_path "amba_pl"
    set is64bit false
    #determine if this is 32 or 64 bit encoding
    if { [expr [string length ${addr}] > 8 ] || 
	 [expr [string first xczu [get_parts -of_objects [get_projects] ] ] >= 0 ] ||
	 [info exists REMOTE_C2C_64] 
     } {
	set is64bit true
    }

    puts ${dtsi_file} "/dts-v1/;"
    puts ${dtsi_file} "/plugin/;"
    puts ${dtsi_file} " "
    puts ${dtsi_file} "/ {"
    puts ${dtsi_file} "	fragment@0 {"
    puts ${dtsi_file} "	    target = <&${amba_path}>;"
    puts ${dtsi_file} "	    __overlay__ {"
    
    puts ${dtsi_file} "       axiSlave$device_name: $device_name@${addr} {"
    if { $is64bit } {
	#figure out how to write 64 bit address in 32bit word chunks
	set addr_MSB  [string range ${addr} 8 [string length ${addr}]]
	if { [expr [string length $addr_MSB] == 0 ] } {
	    set addr_MSB "0"
	}
	set addr_LSB  [string range ${addr} 0 7]
	
	set range_MSB [string range ${addr_range} 8 [string length ${addr_range} ] ]
	if { [expr [string length $range_MSB] == 0 ] } {
	    set range_MSB "0"
	}
	set range_LSB [string range ${addr_range} 0 7]    
	
	puts ${dtsi_file} "        reg = <0x${addr_MSB} 0x${addr_LSB} 0x${range_MSB} 0x${range_LSB}>;"
    } else {
	puts ${dtsi_file} "        reg = <0x${addr} 0x${addr_range}>;"
    }

    set map {}
    lappend map {$device_name} $device_name
    #load the dt_data info (by default this is enables generic UIO, but some things like i2c and interrupts override this)
    puts  ${dtsi_file} [string map $map  ${dt_data}]
    puts ${dtsi_file} "      };"
    puts ${dtsi_file} "    };"
    puts ${dtsi_file} "  };"
    puts ${dtsi_file} "};"


    close ${dtsi_file}
}

## proc \c ComputeAddressRange
# This function computes the lowest address (upvals as base_addr) and the highest addres - lowest (upvals as addr_range)
proc ComputeAddressRange {} {
    global axi_memory_mappings_addr
    global axi_memory_mappings_range

    upvar 1 base_addr base_addr
    set base_addr 0xFFFFFFFFFFFFFFFF
    set max_addr 0
    foreach {slave addr} ${axi_memory_mappings_addr} {
	#find the lowest starting address
	if {$addr < $base_addr} {
	    set base_addr $addr
	}
	
	#find the highest possible address
	set slave_range [dict get ${axi_memory_mappings_range} $slave]
	set slave_end_addr [expr {$addr + $slave_range}]
	if {$slave_end_addr > $max_addr} {
	    set max_addr $slave_end_addr
	}
    }    
    upvar 1 addr_range addr_range
    set addr_range [expr {$max_addr - $base_addr}]
}

## proc \c GENERATE_AXI_ADDR_MAP_C
#Arguments:
#  \param outFileName Name of file to write mapping to
# This function generates a C header file with all the endpoint names and addr/range info
proc GENERATE_AXI_ADDR_MAP_C {outFileName} {
    global axi_memory_mappings_addr
    global axi_memory_mappings_range
    file mkdir [file dirname ${outFileName}]
    set outFile [open ${outFileName} w+]
    puts ${outFile} "#ifndef __AXI_ADDR_MAP__" 
    puts ${outFile} "#define __AXI_ADDR_MAP__"

    #compute the base address and the range
    set base_addr 0
    set addr_range 0
    ComputeAddressRange
    set line [concat "#define BASE_ADDR " [format 0x%08X ${base_addr}]]
    puts ${outFile} $line
    set line [concat "#define ADDR_RANGE " [format 0x%08X ${addr_range}]]
    puts ${outFile} $line

    
    foreach {slave addr} ${axi_memory_mappings_addr} {	
	set line [concat "#define AXI_ADDR_${slave} " [format 0x%08X ${addr}]]
	puts ${outFile} $line
    }
    puts ${outFile} "// ranges"
    foreach {slave range} ${axi_memory_mappings_range} {
	set line [concat "#define AXI_RANGE_${slave} " [format 0x%08X ${range}]]
	puts ${outFile} $line
    }
    puts ${outFile} "#endif" 
    close ${outFile}
}

## proc \c GENERATE_AXI_ADDR_MAP_VHDL
#Arguments:
#  \param outFileName Name of file to write mapping to
# This function generates a VHDL package file with all the endpoint names and addr/range info
proc GENERATE_AXI_ADDR_MAP_VHDL {outFileName} {
    global axi_memory_mappings_addr
    global axi_memory_mappings_range
    set outFile [open ${outFileName} w+]
    puts ${outFile} "library ieee;"
    puts ${outFile} "use ieee.std_logic_1164.all;"
    puts ${outFile} "use ieee.numeric_std.all;"
    puts ${outFile} ""
    puts ${outFile} "package AXISlaveAddrPkg is"


    #compute the base address and the range
    set base_addr  0
    set addr_range  0
    ComputeAddressRange
    set line [concat "constant BASE_ADDR : unsigned(31 downto 0) := " [format x\"%08X\" ${base_addr}] ";"]
    puts ${outFile} $line
    set line [concat "constant ADDR_RANGE : unsigned(31 downto 0) := " [format x\"%08X\" ${addr_range}] ";"]
    puts ${outFile} $line

    
    foreach {slave addr} ${axi_memory_mappings_addr} {
	set line [concat "constant AXI_ADDR_${slave} : unsigned(31 downto 0) := " [format x\"%08X\" ${addr}] ";"]
	puts ${outFile} $line
    }
    puts ${outFile} "-- ranges"
    foreach {slave range} ${axi_memory_mappings_range} {
	set line [concat "constant AXI_RANGE_${slave} : unsigned(31 downto 0) :=  " [format x\"%08X\" ${range}] ";"]
	puts ${outFile} $line
    }
    puts ${outFile} "end package AXISlaveAddrPkg;" 
    close ${outFile}
}

## proc \c GENERATE_AXI_ADDR_MAP_VERILOG
#Arguments:
#  \param outFileName Name of file to write mapping to
# This function generates a VHDL package file with all the endpoint names and addr/range info
proc GENERATE_AXI_ADDR_MAP_VERILOG {outFileName} {
    global axi_memory_mappings_addr
    global axi_memory_mappings_range
    set outFile [open ${outFileName} w+]
    
    puts ${outFile} "`default_nettype none"
    puts ${outFile} "//Autogenerated file, do not edit"
    puts ${outFile} ""
    puts ${outFile} "package AXISlaveAddrPkg ;"

    #compute the base address and the range
    set base_addr  0
    set addr_range  0
    ComputeAddressRange
    set line [concat "parameter logic [31:0] BASE_ADDR = " [format 32'h%08X ${base_addr}] ";"]
    puts ${outFile} $line
    set line [concat "parameter logic [31:0] ADDR_RANGE = " [format 32'h%08X ${addr_range}] ";"]
    puts ${outFile} $line

    
    foreach {slave addr} ${axi_memory_mappings_addr} {
	set line [concat "parameter logic [31:0] AXI_ADDR_${slave} = " [format 32'h%08X ${addr}] ";"]	
	puts ${outFile} $line
    }
    puts ${outFile} "// ranges"
    foreach {slave range} ${axi_memory_mappings_range} {
	set line [concat "parameter logic [31:0] AXI_RANGE_${slave} =  " [format 32'h%08X ${range}] ";"]
	puts ${outFile} $line
    }
    puts ${outFile} "endpackage"
    puts ${outFile} "`default_nettype wire"
    close ${outFile}
}
